### ISSUE TITLE
"Print Inventory" and "Buy a Product" Price Discrepancies

### ISSUE THREAD

**Issue by Jotr4184** [SCCoyle/Coyle_CSCI2270_FinalProject#1]
When testing the program when you buy a product and the price goes up, the price printed out that says "The new price is _____ and there are ____ left", that price is slightly off from the price that is listed when you select the "Print Inventory" and it displays the prices of each item. This price discrepancy seems to compound and the price displayed when you "buy a product" and the prices displayed when you "print inventory" get continuously more off from each other as time goes by and the more you buy.

**Comment by SCCoyle** [comment]
I think what you are seeing in the price discrepancy is the natural decay of all of the prices. It gets worse as time goes on because as the prices go higher the difference between running 1 & 3 go higher.I tested this to make sure that there was no difference between the two by making printing the inventory part of buying a coin.
